spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: d74141bd4e9396138ccc
            client-secret: 3907354b4e35be34165bc9880441ab1724e589a6
          custom:
            client-id: a3885c28332f11e98285000c29c09b61
            client-secret: test
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            authentication-method: header
            redirect-uri: http://oauth2login/login/oauth2/code/custom
            scope: test
            provider: custom
        provider:
          custom:
            authorization-uri: http://oauth2provider/oauth/authorize
            token-uri: http://oauth2provider/oauth/token
            jwk-set-uri: http://localhost/.well-known/jwks.json
            user-info-uri: http://oauth2resource/userinfo
            user-name-attribute: username
server:
  port: 8084
logging:
  level:
    root: INFO
    org.springframework: DEBUG